# Generated by Django 3.2.2 on 2021-07-31 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('marvel_id', models.PositiveIntegerField(default=1, unique=True, verbose_name='marvel ids')),
                ('title', models.CharField(default='', max_length=120, verbose_name='titles')),
                ('description', models.TextField(default='', verbose_name='descriptions')),
                ('price', models.FloatField(default=0.0, max_length=5, verbose_name='prices')),
                ('stock_qty', models.PositiveIntegerField(default=0, verbose_name='stock qty')),
                ('picture', models.URLField(default='', verbose_name='pictures')),
            ],
            options={
                'db_table': 'e_commerce_comics',
            },
        ),
        migrations.CreateModel(
            name='wish_list',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('favorite', models.BooleanField(default=False, verbose_name='Favorite')),
                ('cart', models.BooleanField(default=False, verbose_name='carts')),
                ('wished_qty', models.PositiveIntegerField(default=0, verbose_name='wished qty')),
                ('buied_qty', models.PositiveIntegerField(default=0, verbose_name='buied qty')),
                ('comic_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='e_commerce.comic', verbose_name='Comic')),
                ('user_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'e_commerce_wish_list',
            },
        ),
    ]
